### ISSUE TITLE
终端执行gradlew bintrayUpload，不是在androidstudio执行的，仍然出现javadoc.jar could not be found

### ISSUE THREAD

**Issue by flyingshare** [panpf/android-library-publish-to-jcenter#12]
Parallel execution with configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.esolving dependencies ':app:classpath'
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:app:bintrayUpload
:app:bintrayUpload: file C:\Android\workspace\android\MyLibrary\app\build\libs\app-1.0-javadoc.jar could not be found.
:app:bintrayUpload: file C:\Android\workspace\android\MyLibrary\app\build\libs\app-1.0-sources.jar could not be found.
:app:bintrayUpload FAILED

接着尝试使用gradlew install，结果一堆不存在
程序包android.support.v4.widget不存在
程序包android.support.v7.app不存在
程序包com.google.gson不存在

项目用到了其他依赖库

**Comment by xiaopansky** [comment]
根据前面的异常信息显示，应该是你的NDK有些问题，导致前面的构建失败，你需要先把这个问题解决了
